### PR TITLE
GitHub Actions for MiniScaffold itself

### PR DESCRIPTION
**Pull request by rojepp**
## Proposed Changes

This builds MiniScaffold itself with GitHub Actions on Ubuntu, MacOS and Windows. 
It's the first step of #143. 
[Test Run](https://github.com/rojepp/MiniScaffold/commit/56a680a8e10e47d0086b8b71250284c587babe26/checks)
The next step is to have the templates do the same. 
GitHub actions is in beta and is scheduled to be released Nov 13. One can apply for the beta [here](https://github.com/features/actions). There is no waiting list any longer according to Nat Friedman.

There is a workaround in the workflow right now because of a bug in [setup-dotnet](https://github.com/actions/setup-dotnet/). [PR here](https://github.com/actions/setup-dotnet/pull/34). Once the bug is fixed, the `DOTNET_ROOT` line below can be removed in two places.  

```yaml
      env:
        # Work around https://github.com/actions/setup-dotnet/issues/29
        DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
```

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] Build and tests pass locally
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Further comments

This PR includes the changes in #144, so if those changes aren't acceptable I'll have some rebasing to do. 😅

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
If I just opt into the actions beta and these files exist, it should just work?

**Comment by rojepp** [comment]
@TheAngryByrd That's the plan anyway. ;-) I know there have been some issues around getting Actions to build on forks. Let me know when you've signed up, we'll see what happens.

**Comment by rojepp** [comment]
@TheAngryByrd https://twitter.com/natfriedman/status/1174158823877042177

**Comment by TheAngryByrd** [comment]
the page doesn’t want to load. I’ve submitted an issue to GitHub so we’ll see where that ends up. Thanks for the work 😊

**Comment by rojepp** [comment]
This link doesn't work? https://github.com/features/actions/signup/?account=TheAngryByrd

**Comment by rojepp** [comment]
@TheAngryByrd Ah I just now saw that it actually built.

**Comment by TheAngryByrd** [comment]
So my script blocker was blocking the page :), LGTM now

**Pull request merged**
