### PR TITLE
Make build.sh executable via post-action

### LINKED ISSUE #19: "dotnet new mini-scaffold" on Linux strips execute bit from build.sh
The build.sh file checked into the Git repo has the execute bit properly set, but after I run `dotnet new -i "MiniScaffold::*"` and then `dotnet new mini-scaffold`, the resulting files have build.sh without the execute bit. This is just a minor annoyance as it's easy to immediately run `chmod +x build.sh`, but if it can be fixed in the template that would be nice.

I rather suspect, though, that this is a limitation in the dotnet templating engine, in which case you can't fix it in the template. If that's the case, feel free to just close this issue. :-)

System info:

**Dotnet version:** 2.0.0-preview2-006497
**OS version:** Linux Mint 18.1 (based on Ubuntu Xenial 16.04)

### PR DESCRIPTION
**Pull request by rmunn**
See https://github.com/dotnet/templating/wiki/Post-Action-Registry#change-file-permissions for details. This should fix #19.

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
🎸

**Comment by TheAngryByrd** [comment]
@rmunn just released `0.4.1-beta002` if you want to test it out

**Comment by rmunn** [comment]
Tried out `0.4.1-beta002` by downloading the NuGet package manually and then running `dotnet new -i /home/rmunn/Downloads/miniscaffold.0.4.1-beta002.nupkg`. (I couldn't figure out how to get `dotnet new` to give me prerelease NuGets; running `dotnet new -i "MiniScaffold::*"` just gave me 0.4.0). It opened up with an executable build.sh file. Had a different problem, which I also encountered with 0.4.0, where the FAKE package didn't get restored so build.sh failed — but I'll open a separate bug report for that one. As far as the post-install script goes, it works.

And BTW, if anyone tries to install this via `dotnet new` on .Net Core versions before 2.0.0, they won't get an exectuable build.sh script (because that particular post-action was introduced in .Net Core 2.0.0), but they *will* see the "Run 'chmod +x *.sh'" text associated with that post-action. Props to the .Net Core team for thinking through how that would work and putting forward-compatibility into their post-action system.

**Comment by TheAngryByrd** [comment]
I think if you give it the "exact" version.  ``dotnet new -i MiniScaffold::0.4.1-beta002`

**Comment by TheAngryByrd** [comment]
Also I'll make a note in the readme about it! Thanks!

**Comment by rmunn** [comment]
Apparently the condition should have been `"(OS != \"Windows_NT\")"` (see https://github.com/dotnet/templating/issues/1421#issuecomment-367404828). I've opened PR #51 to fix that mistake.

**Pull request merged**
